### ISSUE TITLE
Resolve the rules about incoming requests

### ISSUE THREAD

**Issue by varokas** [bigbearsio/strength#3]
Do we require the accepting service to have only 1 url? 

1. (1 url) - The load balancers won't be a breaking point (or you need to write or use better load balancers. 
2. (multi-url) - Allow contestants to specify different urls the load testing service points to.

**Comment by supaket** [comment]
Dont understand on this point

**Comment by varokas** [comment]
If we dont allow contentants to use external load balancers, that means all incoming traffic will be route to one VM ?

**Comment by varokas** [comment]
after meeting. we think we'll go for 1-url endpoint
