### ISSUE TITLE
Add Network / Architecture Diagram

### ISSUE THREAD

**Issue by supaket** [bigbearsio/strength#5]
How we score in difference network, where is our server location?

**Comment by varokas** [comment]
I think we simply will just host it in the same cloud and subnet

**Comment by udomsak** [comment]
Another issue , DNS name resolver latency may be affect some.  ^_^

**Comment by supaket** [comment]
Ok @varokas, I assume that we provide their servers and our close environment. They need to deploy on our provide env. 

@udomsak we can simoly fix host name resolved instread of dns.

**Comment by udomsak** [comment]
@supaket Ok ^_^

**Comment by varokas** [comment]
@supaket can u help create pr with RULES.md file with details from the slide plus this Issue please? So we can all review

**Comment by varokas** [comment]
ref: #7. let's put in README.md

**Comment by varokas** [comment]
https://github.com/bigbearsio/strength/pull/8

@supaket looks good?

**Comment by varokas** [comment]
To p mhee to add architecture diagram to README.md

**Comment by mahasak** [comment]
I will discuss with cloud provider to design network for load testing

**Comment by varokas** [comment]
@mahasak - review this please?

https://docs.google.com/presentation/d/1DFFFEJuC18ChHPYVwxVwXADpVpI9UT6BrYqTUS4rVzc/edit#slide=id.g3ba37e93ff_0_1

<img width="1468" alt="screen shot 2018-06-02 at 12 21 55 pm" src="https://user-images.githubusercontent.com/1317078/40880094-9b524aae-665f-11e8-803e-0092e4e82580.png">

**Comment by supaket** [comment]
Reviewing

**Comment by varokas** [comment]
this has been here for a while. let's close.
